# Generated by .github/workflows/release-cli.yml on every cli-v tag.
# Do not edit by hand: the next release overwrites it.
class Mjolnir < Formula
  desc "Inspect and edit the Blam tag data inside an installed copy of Halo Campaign Evolved"
  homepage "https://mjolnircore.com"
  license "MIT"
  version "0.4.0"

  on_macos do
    url "https://github.com/devnull9090/mjolnir-core/releases/download/cli-v0.4.0/mjolnir-0.4.0-macos-universal.tar.gz"
    sha256 "c3814058661e08d5c7adf500cb38d2dc222acc7551451bed004bb4ba8103c79c"
  end

  on_linux do
    url "https://github.com/devnull9090/mjolnir-core/releases/download/cli-v0.4.0/mjolnir-0.4.0-linux-x64.tar.gz"
    sha256 "79241cd6a03e3f24e7ffa534b6ce81affaebe3bd341ddcd069998ca9cbd0bf34"
  end

  def install
    bin.install "mjolnir"
    (share/"mjolnir/defs/hce").install "defs/hce/scripting.json"
    (share/"doc/mjolnir").install "LICENSE"
  end

  test do
    assert_match "mjolnir #{version}", shell_output("#{bin}/mjolnir --version")
  end
end
