# Generated by .github/workflows/release-cli.yml on every cli-v tag.
# Do not edit by hand: the next release overwrites it.
class Mjolnir < Formula
  desc "Inspect and edit the Blam tag data inside an installed copy of Halo Campaign Evolved"
  homepage "https://mjolnircore.com"
  license "MIT"
  version "0.2.0"

  on_macos do
    url "https://github.com/devnull9090/mjolnir-core/releases/download/cli-v0.2.0/mjolnir-0.2.0-macos-universal.tar.gz"
    sha256 "dddad7c228033d6d86c92bfa9c5dfd3dc8bab0bc37ebfde3169149e8b2cf5c60"
  end

  on_linux do
    url "https://github.com/devnull9090/mjolnir-core/releases/download/cli-v0.2.0/mjolnir-0.2.0-linux-x64.tar.gz"
    sha256 "1d81eb8955eab1e58234b1a55bb79d14fc110ae5a223a7c4bf5f9035276c46e0"
  end

  def install
    bin.install "mjolnir"
    (share/"mjolnir/defs/hce").install "defs/hce/scripting.json"
    (share/"doc/mjolnir").install "LICENSE"
  end

  test do
    assert_match "mjolnir #{version}", shell_output("#{bin}/mjolnir --version")
  end
end
