# Generated by .github/workflows/release-cli.yml on every cli-v tag.
# Do not edit by hand: the next release overwrites it.
class Mjolnir < Formula
  desc "Inspect and edit the Blam tag data inside an installed copy of Halo Campaign Evolved"
  homepage "https://mjolnircore.com"
  license "MIT"
  version "0.3.0"

  on_macos do
    url "https://github.com/devnull9090/mjolnir-core/releases/download/cli-v0.3.0/mjolnir-0.3.0-macos-universal.tar.gz"
    sha256 "434ecb5b045fd78ac76a38dc0df1fd80cb66800c0a661480d48b22e60d1d7997"
  end

  on_linux do
    url "https://github.com/devnull9090/mjolnir-core/releases/download/cli-v0.3.0/mjolnir-0.3.0-linux-x64.tar.gz"
    sha256 "58d68458a1a27fe77ea6698f4e562a372e41250f0b43b30c70d991a21254a1f3"
  end

  def install
    bin.install "mjolnir"
    (share/"mjolnir/defs/hce").install "defs/hce/scripting.json"
    (share/"doc/mjolnir").install "LICENSE"
  end

  test do
    assert_match "mjolnir #{version}", shell_output("#{bin}/mjolnir --version")
  end
end
