//! The built-in decoder is what runs when no `oo2core_*_win64.dll` is around,
//! which is the default for most people. This checks it against a known answer
//! without needing either the DLL or the game installed.
//!
//! `fixtures/kraken.bin` is `synthetic(48 KiB)` below, compressed by the real
//! Oodle encoder with Kraken at Normal. It holds no game content — the input is
//! generated by the LCG in this file, so the expected output is recomputed
//! rather than stored.

use std::path::PathBuf;

/// Deterministic, mildly compressible bytes: an LCG with repeated runs, so the
/// encoder emits both literals and matches rather than one trivial case.
fn synthetic(len: usize) -> Vec<u8> {
    let mut out = Vec::with_capacity(len);
    let mut state: u32 = 0x1234_5678;
    while out.len() < len {
        state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        let byte = (state >> 24) as u8;
        let run = 1 + (state % 17) as usize;
        for _ in 0..run {
            out.push(byte);
            if out.len() == len {
                break;
            }
        }
        if out.len() > 512 && state % 5 == 0 {
            let start = (state as usize) % (out.len() - 256);
            let slice: Vec<u8> = out[start..start + 128].to_vec();
            out.extend_from_slice(&slice);
            out.truncate(len);
        }
    }
    out
}

fn fixture() -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("kraken.bin");
    std::fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

#[test]
fn built_in_decoder_reproduces_the_input_with_no_dll() {
    let expected = synthetic(48 * 1024);
    // No search roots, so there is no DLL to fall back from.
    let got = ue_iostore::oodle::decompress(&fixture(), expected.len(), &[])
        .expect("built-in decode");
    assert_eq!(got.len(), expected.len());
    assert!(got == expected, "decoded bytes differ from the input");
}

#[test]
fn no_search_roots_means_the_built_in_decoder() {
    assert_eq!(
        ue_iostore::oodle::backend(&[]),
        ue_iostore::oodle::Backend::Pure
    );
}

#[test]
fn a_short_output_buffer_is_an_error_not_a_panic() {
    // Asking for fewer bytes than the stream holds must fail cleanly; this is
    // the shape of a corrupt or mismatched block entry.
    let result = ue_iostore::oodle::decompress(&fixture(), 1024, &[]);
    assert!(result.is_err(), "expected an error, got {result:?}");
}

#[test]
fn garbage_input_is_an_error_not_a_panic() {
    let junk: Vec<u8> = (0..4096u32).map(|i| (i * 7) as u8).collect();
    let result = ue_iostore::oodle::decompress(&junk, 48 * 1024, &[]);
    assert!(result.is_err(), "expected an error, got {result:?}");
}
