//! The Blam script a `scenario` tag carries, shaped for the editor.
//!
//! A scenario ships its scripting twice: the original `.hsc` text in `source
//! files`, and the compiled expression tree the game runs. The editor shows the
//! text — it is the real thing, comments and all — and falls back to
//! decompiling the tree only when a scenario has no source, which is what a
//! stripped or hand-built mod looks like.
//!
//! The function table lives in `defs/hce/scripting.json` and is baked in at
//! build time. It is schema, not content: opcodes and type names, no script
//! bodies. Without it the decompiler cannot tell a quoted literal from a bare
//! one, so it is a build input rather than something to look up at runtime.

use std::sync::OnceLock;

use blam_hsc::lex::{self, Token};
use blam_hsc::ScriptCorpus;
use serde::Serialize;

/// The recovered scripting corpus, generated by `mjolnir scripting`.
const SCRIPTING_JSON: &str = include_str!("../../../../defs/hce/scripting.json");

/// The corpus, parsed once.
///
/// A corpus that fails to parse is not fatal: the editor still shows the source
/// files, which is the main thing. Only the decompiler degrades.
pub fn corpus() -> Option<&'static ScriptCorpus> {
    static CORPUS: OnceLock<Option<ScriptCorpus>> = OnceLock::new();
    CORPUS
        .get_or_init(|| serde_json::from_str(SCRIPTING_JSON).ok())
        .as_ref()
}

#[derive(Debug, Clone, Serialize)]
pub struct SourceFile {
    pub name: String,
    pub text: String,
    pub lines: usize,
    pub bytes: usize,
    /// The tag's own flags for this file: generated at runtime, AI fragments,
    /// AI performances.
    pub flags: Vec<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ScriptDecl {
    pub name: String,
    /// `startup`, `dormant`, `static`, `command_script`, and so on.
    pub kind: String,
    pub return_type: String,
    /// Rendered as `short delay`, in declaration order.
    pub parameters: Vec<String>,
    /// Which source file declares it, and on what line, when it can be found.
    pub file: Option<String>,
    pub line: Option<usize>,
}

#[derive(Debug, Clone, Serialize)]
pub struct GlobalDecl {
    pub name: String,
    pub value_type: String,
    pub initializer: String,
    pub file: Option<String>,
    pub line: Option<usize>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ScriptView {
    pub path: String,
    pub source_files: Vec<SourceFile>,
    pub scripts: Vec<ScriptDecl>,
    pub globals: Vec<GlobalDecl>,
    /// Tags the scripts reference.
    pub references: Vec<String>,
    /// Live expressions, and the datum slots they occupy.
    pub expressions: usize,
    pub datum_slots: usize,
    pub string_bytes: usize,
    /// Whether the tag carries the source it was compiled from. When false the
    /// editor shows decompiled output and says so.
    pub has_source: bool,
}

const FILE_FLAGS: [&str; 3] = ["generated at runtime", "ai fragments", "ai performances"];

fn flag_names(bits: u32) -> Vec<String> {
    FILE_FLAGS
        .iter()
        .enumerate()
        .filter(|(i, _)| bits & (1 << i) != 0)
        .map(|(_, name)| name.to_string())
        .collect()
}

/// Where each declaration sits in the source, so the editor can jump to it.
///
/// Found by scanning tokens rather than by matching text, so a `(script` inside
/// a comment or a string cannot produce a phantom entry. A name can appear more
/// than once — HSC overloads on arity — and the first occurrence wins, which is
/// what "jump to definition" should land on.
struct Declarations {
    scripts: std::collections::HashMap<String, (String, usize)>,
    globals: std::collections::HashMap<String, (String, usize)>,
}

impl Declarations {
    fn scan(files: &[blam_hsc::SourceFile], value_types: &[String]) -> Self {
        let types: std::collections::HashSet<&str> =
            value_types.iter().map(String::as_str).collect();
        let mut out = Declarations {
            scripts: std::collections::HashMap::new(),
            globals: std::collections::HashMap::new(),
        };

        for file in files {
            let text = file.text();
            let lexemes = lex::tokenize(&text);
            for (i, l) in lexemes.iter().enumerate() {
                if l.token != Token::Open {
                    continue;
                }
                let Some(Token::Word(head)) = lexemes.get(i + 1).map(|l| &l.token) else {
                    continue;
                };
                let (target, name_at) = match head.as_str() {
                    // ( script <kind> [<return>] <name>
                    "script" => {
                        let mut at = i + 2;
                        if let Some(Token::Word(kind)) = lexemes.get(at).map(|l| &l.token) {
                            at += 1;
                            if matches!(kind.as_str(), "static" | "stub") {
                                if let Some(Token::Word(w)) = lexemes.get(at).map(|l| &l.token) {
                                    if types.contains(w.as_str()) {
                                        at += 1;
                                    }
                                }
                            }
                        }
                        // A parameterised script wraps its name in a list.
                        if lexemes.get(at).map(|l| &l.token) == Some(&Token::Open) {
                            at += 1;
                        }
                        (&mut out.scripts, at)
                    }
                    // ( global <type> <name>
                    "global" => (&mut out.globals, i + 3),
                    _ => continue,
                };
                if let Some(Token::Word(name)) = lexemes.get(name_at).map(|l| &l.token) {
                    target
                        .entry(name.clone())
                        .or_insert((file.name.clone(), l.line as usize));
                }
            }
        }
        out
    }
}

/// Build the editor's view of one scenario's scripting.
pub fn view(
    path: String,
    layout: &blam_tag::Layout<'_>,
    block: &blam_tag::data::Block<'_>,
) -> Result<ScriptView, String> {
    let hs = blam_hsc::read::read(layout, block).map_err(|e| e.to_string())?;
    let decls = Declarations::scan(&hs.source_files, hs.value_types.names());
    let type_name = |t: u16| hs.value_types.name_of(t).unwrap_or("unknown").to_string();

    let decompiler = match corpus() {
        Some(c) => blam_hsc::Decompiler::with_corpus(&hs, c),
        None => blam_hsc::Decompiler::new(&hs),
    };

    let source_files: Vec<SourceFile> = hs
        .source_files
        .iter()
        .map(|f| {
            let text = f.text().into_owned();
            SourceFile {
                name: f.name.clone(),
                lines: text.lines().count(),
                bytes: f.source.len(),
                flags: flag_names(f.flags),
                text,
            }
        })
        .collect();

    // A source file holding a single space is the cooker's placeholder for one
    // that was never written; it is not source the user can read.
    let has_source = source_files.iter().any(|f| f.text.trim().len() > 1);

    let scripts = hs
        .scripts
        .iter()
        .map(|s| {
            let (file, line) = match decls.scripts.get(&s.name) {
                Some((f, l)) => (Some(f.clone()), Some(*l)),
                None => (None, None),
            };
            ScriptDecl {
                name: s.name.clone(),
                kind: hs
                    .script_types
                    .name_of(s.script_type)
                    .unwrap_or("unknown")
                    .to_string(),
                return_type: type_name(s.return_type),
                parameters: s
                    .parameters
                    .iter()
                    .map(|p| format!("{} {}", type_name(p.value_type), p.name))
                    .collect(),
                file,
                line,
            }
        })
        .collect();

    let globals = hs
        .globals
        .iter()
        .map(|g| {
            let (file, line) = match decls.globals.get(&g.name) {
                Some((f, l)) => (Some(f.clone()), Some(*l)),
                None => (None, None),
            };
            GlobalDecl {
                name: g.name.clone(),
                value_type: type_name(g.value_type),
                initializer: decompiler.global(g),
                file,
                line,
            }
        })
        .collect();

    let mut source_files = source_files;
    if !has_source {
        // Nothing readable shipped, so show what the tree says instead. Named
        // distinctly so it is never mistaken for the original.
        let text = decompiler.scenario();
        source_files.push(SourceFile {
            name: "<decompiled>".to_string(),
            lines: text.lines().count(),
            bytes: text.len(),
            flags: vec!["decompiled from the expression tree".to_string()],
            text,
        });
    }

    Ok(ScriptView {
        path,
        source_files,
        scripts,
        globals,
        references: hs.references.clone(),
        expressions: hs.live().count(),
        datum_slots: hs.expressions.len(),
        string_bytes: hs.strings.len(),
        has_source,
    })
}

/// Decompile one script by name, for comparing against the shipped source.
pub fn decompile_one(
    layout: &blam_tag::Layout<'_>,
    block: &blam_tag::data::Block<'_>,
    name: &str,
) -> Result<String, String> {
    let hs = blam_hsc::read::read(layout, block).map_err(|e| e.to_string())?;
    let d = match corpus() {
        Some(c) => blam_hsc::Decompiler::with_corpus(&hs, c),
        None => blam_hsc::Decompiler::new(&hs),
    };
    hs.scripts
        .iter()
        .find(|s| s.name == name)
        .map(|s| d.script(s))
        .ok_or_else(|| format!("no script named {name:?}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_baked_in_corpus_parses_and_has_a_function_table() {
        let c = corpus().expect("defs/hce/scripting.json should parse");
        assert!(c.functions.len() > 400, "got {}", c.functions.len());
        assert!(!c.value_types.is_empty());
        // The table is only valid for the build it came from, so it must say
        // which one.
        assert!(!c.build.is_empty());
    }

    #[test]
    fn begin_is_opcode_zero_as_every_blam_build_has_it() {
        let c = corpus().unwrap();
        assert_eq!(c.functions.get(&0).map(|f| f.name.as_str()), Some("begin"));
    }

    fn files(items: &[(&str, &str)]) -> Vec<blam_hsc::SourceFile> {
        items
            .iter()
            .map(|(name, text)| blam_hsc::SourceFile {
                name: name.to_string(),
                source: text.as_bytes().to_vec(),
                flags: 0,
            })
            .collect()
    }

    fn types() -> Vec<String> {
        ["void", "boolean", "short", "ai"]
            .iter()
            .map(|s| s.to_string())
            .collect()
    }

    #[test]
    fn declarations_are_found_with_their_file_and_line() {
        let f = files(&[(
            "a30",
            "; a comment\n(global boolean b_awake false)\n\n(script dormant on_wake\n\t(wake x)\n)\n",
        )]);
        let d = Declarations::scan(&f, &types());
        assert_eq!(d.globals.get("b_awake"), Some(&("a30".into(), 2)));
        assert_eq!(d.scripts.get("on_wake"), Some(&("a30".into(), 4)));
    }

    #[test]
    fn a_parameterised_script_declares_its_name_not_its_first_parameter_type() {
        let f = files(&[("g", "(script static void (f_a (short n))\n\t(wake x)\n)")]);
        let d = Declarations::scan(&f, &types());
        assert_eq!(d.scripts.get("f_a"), Some(&("g".into(), 1)));
        assert!(!d.scripts.contains_key("short"));
        assert!(!d.scripts.contains_key("void"));
    }

    #[test]
    fn a_script_mentioned_in_a_comment_is_not_a_declaration() {
        let f = files(&[("g", "; (script dormant ghost\n(script dormant real_one\n)")]);
        let d = Declarations::scan(&f, &types());
        assert!(!d.scripts.contains_key("ghost"));
        assert!(d.scripts.contains_key("real_one"));
    }

    #[test]
    fn an_overloaded_name_resolves_to_its_first_declaration() {
        let f = files(&[(
            "g",
            "(script static void (f_a (short n))\n)\n(script static void (f_a (short n) (ai w))\n)",
        )]);
        let d = Declarations::scan(&f, &types());
        assert_eq!(d.scripts.get("f_a"), Some(&("g".into(), 1)));
    }

    #[test]
    fn file_flags_decode_to_their_names() {
        assert!(flag_names(0).is_empty());
        assert_eq!(flag_names(0b010), vec!["ai fragments"]);
        assert_eq!(
            flag_names(0b101),
            vec!["generated at runtime", "ai performances"]
        );
    }
}
